BAIDU_TRANSLATE_API_URL = "https://fanyi-api.baidu.com/api/trans/vip/translate"

DEFAULT_APP_ID = "YOUR_APP_ID"
DEFAULT_SECRET_KEY = "YOUR_SECRET_KEY"

APP_NAME = "QuickTranslator"
APP_VERSION = "1.0.0"

ORG_NAME = "QuickTranslator"
DOMAIN = "quicktranslator.com"

TRANSLATE_ENGINE_BAIDU = "baidu"
TRANSLATE_ENGINE_YOUDAO = "youdao"
TRANSLATE_ENGINE_GOOGLE = "google"

DEFAULT_TRANSLATE_ENGINE = TRANSLATE_ENGINE_BAIDU

SUPPORTED_ENGINES = [
    TRANSLATE_ENGINE_BAIDU,
    TRANSLATE_ENGINE_YOUDAO,
    TRANSLATE_ENGINE_GOOGLE,
]

LANG_AUTO = "auto"
LANG_ZH = "zh"
LANG_EN = "en"

MAX_TEXT_LENGTH = 6000

WINDOW_MAX_WIDTH = 500
WINDOW_MAX_HEIGHT = 400

WINDOW_PADDING = 10
WINDOW_OFFSET_X = 15
WINDOW_OFFSET_Y = 15

REQUEST_TIMEOUT = 10
